name: Issue Ready Release

on:
  issues:
    types: [labeled]

jobs:
  create-comment:
    runs-on: ubuntu-latest
    if: github.event.label.name == 'ready release'
    steps:
      - name: Create comment
        uses: actions-cool/issues-helper@v1.7
        with:
          actions: 'create-comment'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          body: |
            Hello @${{ github.event.issue.user.login }}, This bug has been fixed and will be released together with the next release.
            你好 @${{ github.event.issue.user.login }}，这个bug已经修复, 会在下个版本一起发布。

      - name: Remove labels
        uses: actions-cool/issues-helper@v1.7
        with:
          actions: 'remove-labels'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          labels: 'Progress,help wanted'
